// let age = 32;
// console.log("my age is " + age);
// var hej = "VAR can have local or global scope";
// let hello =
//   "LET can have local, global or block scope. Let is preferred over VAR";
// const hejsan = "Use CONST for variables that should not be reassigned";
// console.log(hej);
// console.log(hejsan);
// console.log(hello);
// let iBool = true;
// let iString = "a string much wow";
// let iNum = 256;
// console.log(iBool);
// console.log(iString);
// console.log(iNum);
// const name = "Namnet";
// name = "Ett annat namn";
// let number1 = 31;
// let number2 = 11;
// let result1 = number1 - number2;
// let result2 = number1 * number2;
// let result3 = number1 / number2;
// console.log(result1);
// console.log(result2);
// console.log(result3);
let a = 12;
a += 5;
console.log(a);
